---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd
  healthChecks:
    - kind: Deployment
      name: prometheus
      namespace: linkerd-viz
  interval: 1m0s
  path: ./infrastructure/linkerd-viz
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
