apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  labels:
    linkerd.io/extension: viz
    name: linkerd-viz
  annotations:
    config.linkerd.io/proxy-await: enabled
    linkerd.io/inject: enabled
