apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flagger
  namespace: linkerd
spec:
  interval: 10m
  url: https://github.com/weaveworks/flagger
  ref:
    tag: v1.9.0
  ignore: |
    /*
    !/kustomize
